language: android
android:
  components:
    - build-tools-21.1.0
    - platform-tools
    - tools
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

notifications:
    email: false

before_install:

  # for gradle output style
  - export TERM=dumb
  - wget https://services.gradle.org/distributions/gradle-2.1-bin.zip
  - unzip gradle-2.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.1
  - export PATH=$GRADLE_HOME/bin:$PATH

script: gradle assembleDebug