language: android
android:
  components:
    - build-tools-21.1.0
    - platform-tools
    - tools
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

notifications:
    email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

script: gradle assembleDebug